### ISSUE TITLE
Something went wrong while executing ElectrumBTH

### ISSUE THREAD

**Issue by Danzzzik** [BTHPOS/electrum#5]
<h2>Traceback</h2>
<pre>
Traceback (most recent call last):
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\util.py", line 770, in run_with_except_hook
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 1035, in run
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 969, in wait_on_sockets
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 627, in process_responses
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 542, in process_response
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 1063, in on_notify_header
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 397, in save_header
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 381, in write
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 61, in write_file
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 379, in write_data
OSError: [Errno 9] Bad file descriptor

</pre>

<h2>Additional information</h2>
<ul>
  <li>ElectrumBTH version: 3.2.1</li>
  <li>Operating system: Windows-10-10.0.17134</li>
  <li>Wallet type: imported</li>
  <li>Locale: ru_RU</li>
  <li>Testnet: False</li>
  <li>Regtest: False</li>
</ul>

**Comment by dondreytaylor** [comment]
Thanks for pointing this out. Sorry for the delay. Are you trying to compile it from scratch or run it from the command line? Our builds currently work at the moment and I know we put out a few builds since then.

**Comment by dondreytaylor** [comment]
Assuming this issue was resolved. Closing for now.
