### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sathebm** [BTHPOS/electrum#6]
<h2>Traceback</h2>
<pre>
Traceback (most recent call last):
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\util.py", line 770, in run_with_except_hook
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 1035, in run
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 969, in wait_on_sockets
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 627, in process_responses
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 573, in process_response
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 879, in on_get_header
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 381, in write
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 61, in write_file
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 377, in write_data
TypeError: a bytes-like object is required, not 'str'

</pre>

<h2>Additional information</h2>
<ul>
  <li>ElectrumBTH version: 3.2.1</li>
  <li>Operating system: Windows-10-10.0.18334</li>
  <li>Wallet type: standard</li>
  <li>Locale: en_US</li>
  <li>Testnet: False</li>
  <li>Regtest: False</li>
</ul>

**Comment by sathebm** [comment]
<h2>Traceback</h2>
<pre>
Traceback (most recent call last):
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\util.py", line 770, in run_with_except_hook
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 1035, in run
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 969, in wait_on_sockets
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 627, in process_responses
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 573, in process_response
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\network.py", line 879, in on_get_header
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 381, in write
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 61, in write_file
  File "site-packages\electrumbth-3.2.1-py3.5.egg\electrum\blockchain.py", line 377, in write_data
TypeError: a bytes-like object is required, not 'str'

</pre>

<h2>Additional information</h2>
<ul>
  <li>ElectrumBTH version: 3.2.1</li>
  <li>Operating system: Windows-10-10.0.18334</li>
  <li>Wallet type: standard</li>
  <li>Locale: en_US</li>
  <li>Testnet: False</li>
  <li>Regtest: False</li>
</ul>

**Comment by dondreytaylor** [comment]
Thanks for pointing this out. Sorry for the delay. Are you trying to compile it from scratch or run it from the command line? Our builds currently work at the moment and I know we put out a few builds since then.

**Comment by dondreytaylor** [comment]
Assuming this issue was resolved. Closing for now.

**Comment by sathebm** [comment]
Its working now. Thnaks
